# Generated by Django 4.2.1 on 2023-05-10 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapp.menuitem'),
        ),
    ]
